# Generated by Django 5.0.3 on 2024-06-10 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_item_last_modified_by_alter_item_user_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified_by',
            field=models.ForeignKey(default=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
